=== UO295662/MOTOGP-DESKTOP/MotoGP-Desktop_final/xml/circuito.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://www.uniovi.es"
	xmlns="http://www.uniovi.es"
	elementFormDefault="qualified">
  <xs:element name="circuito">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="nombre"/>
        <xs:element ref="longitud_pista"/>
        <xs:element ref="anchura"/>
        <xs:element ref="fecha"/>
        <xs:element ref="hora"/>
        <xs:element ref="vueltas"/>
        <xs:element ref="localidad"/>
        <xs:element ref="pais"/>
        <xs:element ref="patrocinador"/>
        <xs:element ref="bibliografia"/>
        <xs:element ref="galeria_fotos"/>
        <xs:element ref="galeria_videos" minOccurs="1" maxOccurs="1"/>
        <xs:element ref="coordenadas_centro"/>
        <xs:element ref="tramos"/>
        <xs:element ref="resultados_carrera"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>


  <xs:element name="nombre">
    <xs:simpleType>
      <xs:restriction base="xs:string">
        <xs:minLength value="5"/>
        <xs:maxLength value="100"/>
      </xs:restriction>
    </xs:simpleType>
  </xs:element>

  <xs:element name="longitud_pista">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="xs:decimal">
          <xs:attribute name="unidad" use="required">
            <xs:simpleType>
              <xs:restriction base="xs:string">
                <xs:enumeration value="metros"/>
              </xs:restriction>
            </xs:simpleType>
          </xs:attribute>
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>

  <xs:element name="anchura">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="xs:decimal">
          <xs:attribute name="unidad" use="required">
            <xs:simpleType>
              <xs:restriction base="xs:string">
                <xs:enumeration value="metros"/>
              </xs:restriction>
            </xs:simpleType>
          </xs:attribute>
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>

  <xs:element name="fecha" type="xs:date"/>
  <xs:element name="hora" type="xs:time"/>
  <xs:element name="vueltas" type="xs:positiveInteger"/>
  <xs:element name="localidad" type="xs:string"/>
  <xs:element name="pais" type="xs:string"/>
  <xs:element name="patrocinador" type="xs:string"/>

  <xs:element name="bibliografia">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="referencia" type="xs:anyURI" minOccurs="3" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="galeria_fotos">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="foto" minOccurs="1" maxOccurs="5"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="foto">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="descripcion" type="xs:string"/>
        <xs:element name="archivo" type="xs:anyURI"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="galeria_videos">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="video" minOccurs="1" maxOccurs="3"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="video">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="descripcion" type="xs:string"/>
        <xs:element name="archivo" type="xs:anyURI"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="coordenadas_centro">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="latitud">
          <xs:simpleType>
            <xs:restriction base="xs:decimal">
              <xs:minInclusive value="-90.0"/>
              <xs:maxInclusive value="90.0"/>
            </xs:restriction>
          </xs:simpleType>
        </xs:element>
        <xs:element name="longitud">
          <xs:simpleType>
            <xs:restriction base="xs:decimal">
              <xs:minInclusive value="-180.0"/>
              <xs:maxInclusive value="180.0"/>
            </xs:restriction>
          </xs:simpleType>
        </xs:element>
        <xs:element name="altitud" type="xs:decimal"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  
  <xs:element name="tramos">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="tramo" minOccurs="1" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="tramo">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="distancia">
          <xs:complexType>
            <xs:simpleContent>
              <xs:extension base="xs:decimal">
                <xs:attribute name="unidad" use="required">
                  <xs:simpleType>
                    <xs:restriction base="xs:string">
                      <xs:enumeration value="metros"/>
                    </xs:restriction>
                  </xs:simpleType>
                </xs:attribute>
              </xs:extension>
            </xs:simpleContent>
          </xs:complexType>
        </xs:element>
        <xs:element name="coordenadas">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="latitud">
                <xs:simpleType>
                  <xs:restriction base="xs:decimal">
                    <xs:minInclusive value="-90.0"/>
                    <xs:maxInclusive value="90.0"/>
                  </xs:restriction>
                </xs:simpleType>
              </xs:element>
              <xs:element name="longitud">
                <xs:simpleType>
                  <xs:restriction base="xs:decimal">
                    <xs:minInclusive value="-180.0"/>
                    <xs:maxInclusive value="180.0"/>
                  </xs:restriction>
                </xs:simpleType>
              </xs:element>
              <xs:element name="altitud" type="xs:decimal"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="sector" type="xs:integer">
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="resultados_carrera">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="vencedor"/>
        <xs:element ref="clasificacion_mundial"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="vencedor">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="nombre"/>
        <xs:element name="tiempo" type="xs:duration"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="clasificacion_mundial">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="piloto" minOccurs="1" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="piloto">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="posicion" type="xs:positiveInteger"/>
        <xs:element ref="nombre"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  
</xs:schema>

=== UO295662/MOTOGP-DESKTOP/MotoGP-Desktop_P9/xml/circuitoEsquema.xml
<?xml version="1.0" encoding="UTF-8"?>
<circuito 
xmlns="http://www.uniovi.es"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="http://www.uniovi.es circuito.xsd"
>
    <nombre>Circuito de Jerez – Angel Nieto</nombre>
    <longitud_pista unidad="metros">5793.0</longitud_pista>
    <anchura unidad="metros">12</anchura>
    <fecha>2025-04-27</fecha>
    <hora>14:00:00</hora>
    <vueltas>25</vueltas>
    <localidad>Jerez de la Frontera</localidad>
    <pais>España</pais>
    <patrocinador>Estrella Galicia 0,0</patrocinador>
    <bibliografia>
        <referencia>https://circuitodejerez.com/circuito/</referencia>
        <referencia>https://es.wikipedia.org/wiki/Circuito_de_Jerez</referencia>
        <referencia>https://www.jerezmotogp.com/es</referencia>
    </bibliografia>
    <galeria_fotos>
        <foto>
            <descripcion>Panorama del circuito</descripcion>
            <archivo>../multimedia/jerez-panoramica.jpg</archivo>
        </foto>
        <foto>
            <descripcion>Recta principal y zona de meta</descripcion>
            <archivo>../multimedia/jerez-recta.jpg</archivo>
        </foto>
        <foto>
            <descripcion>Tribuna</descripcion>
            <archivo>../multimedia/jerez-tribuna.jpg</archivo>
        </foto>
    </galeria_fotos>
    
    <galeria_videos>
        <video>
            <descripcion>Salida del circuito</descripcion>
            <archivo>../multimedia/jerez-salida.mp4</archivo>
        </video>
    </galeria_videos>
    <coordenadas_centro>
        <latitud>36.7103</latitud>
        <longitud>-6.0328</longitud>
        <altitud>40</altitud>
    </coordenadas_centro>
    <tramos>
        <tramo>
            <distancia unidad="metros">237.37</distancia>
            <coordenadas>
                <latitud>36.7122</latitud>
                <longitud>-6.0339</longitud>
                <altitud>45</altitud>
            </coordenadas>
            <sector>1</sector>
        </tramo>
        <tramo>
            <distancia unidad="metros">189.34</distancia>
            <coordenadas>
                <latitud>36.7128</latitud>
                <longitud>-6.0314</longitud>
                <altitud>49</altitud>
            </coordenadas>
            <sector>1</sector>
        </tramo>
        <tramo>
            <distancia unidad="metros">39.43</distancia>
            <coordenadas>
                <latitud>36.7125</latitud>
                <longitud>-6.0311</longitud>
                <altitud>49</altitud>
            </coordenadas>
            <sector>1</sector>
        </tramo>
        <tramo>
            <distancia unidad="metros">37.84</distancia>
            <coordenadas>
                <latitud>36.7122</latitud>
                <longitud>-6.0314</longitud>
                <altitud>46</altitud>
            </coordenadas>
            <sector>1</sector>
        </tramo>
        <tramo>
            <distancia unidad="metros">160.75</distancia>
            <coordenadas>
                <latitud>36.7100</latitud>
                <longitud>-6.0319</longitud>
                <altitud>41</altitud>
            </coordenadas>
            <sector>1</sector>
        </tramo>
        <tramo>
            <distancia unidad="metros">327.28</distancia>
            <coordenadas>
                <latitud>36.7092</latitud>
                <longitud>-6.0278</longitud>
                <altitud>49</altitud>
            </coordenadas>
            <sector>1</sector>
        </tramo>
        <tramo>
            <distancia unidad="metros">124.35</distancia>
            <coordenadas>
                <latitud>36.7081</latitud>
                <longitud>-6.0270</longitud>
                <altitud>53</altitud>
            </coordenadas>
            <sector>2</sector>
        </tramo>
        <tramo>
            <distancia unidad="metros">671.2</distancia>
            <coordenadas>
                <latitud>36.7039</latitud>
                <longitud>-6.0331</longitud>
                <altitud>46</altitud>
            </coordenadas>
            <sector>2</sector>
        </tramo>
        <tramo>
            <distancia unidad="metros">50.92</distancia>
            <coordenadas>
                <latitud>36.7044</latitud>
                <longitud>-6.0333</longitud>
                <altitud>46</altitud>
            </coordenadas>
            <sector>2</sector>
        </tramo>
        <tramo>
            <distancia unidad="metros">239.2</distancia>
            <coordenadas>
                <latitud>36.7064</latitud>
                <longitud>-6.0322</longitud>
                <altitud>41</altitud>
            </coordenadas>
            <sector>2</sector>
        </tramo>
        <tramo>
            <distancia unidad="metros">277.83</distancia>
            <coordenadas>
                <latitud>36.7083</latitud>
                <longitud>-6.0342</longitud>
                <altitud>37</altitud>
            </coordenadas>
            <sector>2</sector>
        </tramo>
        <tramo>
            <distancia unidad="metros">114.16</distancia>
            <coordenadas>
                <latitud>36.7078</latitud>
                <longitud>-6.0353</longitud>
                <altitud>36</altitud>
            </coordenadas>
            <sector>2</sector>
        </tramo>
        <tramo>
            <distancia unidad="metros">228.8</distancia>
            <coordenadas>
                <latitud>36.7061</latitud>
                <longitud>-6.0364</longitud>
                <altitud>40</altitud>
            </coordenadas>
            <sector>3</sector>
        </tramo>
        <tramo>
            <distancia unidad="metros">53.52</distancia>
            <coordenadas>
                <latitud>36.7058</latitud>
                <longitud>-6.0369</longitud>
                <altitud>39</altitud>
            </coordenadas>
            <sector>3</sector>
        </tramo>
        <tramo>
            <distancia unidad="metros">108.46</distancia>
            <coordenadas>
                <latitud>36.7064</latitud>
                <longitud>-6.0378</longitud>
                <altitud>40</altitud>
            </coordenadas>
            <sector>3</sector>
        </tramo>
        <tramo>
            <distancia unidad="metros">290.39</distancia>
            <coordenadas>
                <latitud>36.7089</latitud>
                <longitud>-6.0364</longitud>
                <altitud>34</altitud>
            </coordenadas>
            <sector>3</sector>
        </tramo>
        <tramo>
            <distancia unidad="metros">64.56</distancia>
            <coordenadas>
                <latitud>36.7092</latitud>
                <longitud>-6.0358</longitud>
                <altitud>35</altitud>
            </coordenadas>
            <sector>3</sector>
        </tramo>
        <tramo>
            <distancia unidad="metros">170.35</distancia>
            <coordenadas>
                <latitud>36.7089</latitud>
                <longitud>-6.0339</longitud>
                <altitud>37</altitud>
            </coordenadas>
            <sector>3</sector>
        </tramo>
        <tramo>
            <distancia unidad="metros">57.11</distancia>
            <coordenadas>
                <latitud>36.7072</latitud>
                <longitud>-6.0311</longitud>
                <altitud>40</altitud>
            </coordenadas>
            <sector>3</sector>
        </tramo>
        <tramo>
            <distancia unidad="metros">383.79</distancia>
            <coordenadas>
                <latitud>36.7103</latitud>
                <longitud>-6.0328</longitud>
                <altitud>40</altitud>
            </coordenadas>
            <sector>3</sector>
        </tramo>
    </tramos>
    <resultados_carrera>
        <vencedor>
            <nombre>Álex Márquez</nombre>
            <tiempo>PT33M17.979S</tiempo>
        </vencedor>
        <clasificacion_mundial>
            <piloto>
                <posicion>1</posicion>
                <nombre>Álex Márquez</nombre>
            </piloto>
            <piloto>
                <posicion>2</posicion>
                <nombre>Fabio Quartararo</nombre>
            </piloto>
            <piloto>
                <posicion>3</posicion>
                <nombre>Francesco Bagnaia</nombre>
            </piloto>
        </clasificacion_mundial>
    </resultados_carrera>
</circuito>
